## **%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%**

Considere o dataset a seguir
dataset = [
  ['Milk', 'Onion', 'Nutmeg', 'Eggs', 'Yogurt'],
  ['Dill', 'Onion', 'Nutmeg', 'Eggs', 'Yogurt'],
  ['Milk', 'Apple', 'Eggs'],
  ['Milk', 'Unicorn', 'Corn', 'Yogurt'],
  ['Corn', 'Onion', 'Onion', 'Ice cream', 'Eggs']
  ]

Execute o apriori com suporte mínimo igual a 0.5 e extraia as regras com confiança mínima de
0.7. Quantas regras são geradas e quem são as regras? Segundo a medida conviction, quem é a
melhor regra?

### Carrega o dataset

In [ ]:
dataset = [['Milk', 'Onion', 'Nutmeg', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Ice cream', 'Eggs']]

dataset

[['Milk', 'Onion', 'Nutmeg', 'Eggs', 'Yogurt'],
 ['Dill', 'Onion', 'Nutmeg', 'Eggs', 'Yogurt'],
 ['Milk', 'Apple', 'Eggs'],
 ['Milk', 'Unicorn', 'Corn', 'Yogurt'],
 ['Corn', 'Onion', 'Onion', 'Ice cream', 'Eggs']]

In [ ]:
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

In [ ]:
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

,Apple,Corn,Dill,Eggs,Ice cream,Milk,Nutmeg,Onion,Unicorn,Yogurt
0,False,False,False,True,False,True,True,True,False,True
1,False,False,True,True,False,False,True,True,False,True
2,True,False,False,True,False,True,False,False,False,False
3,False,True,False,False,False,True,False,False,True,True
4,False,True,False,True,True,False,False,True,False,False

In [ ]:
frequent_itemsets = apriori(df, min_support=0.5, use_colnames=True)
frequent_itemsets

   support       itemsets
0      0.8         (Eggs)
1      0.6         (Milk)
2      0.6        (Onion)
3      0.6       (Yogurt)
4      0.6  (Onion, Eggs)

In [ ]:
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets

   support       itemsets  length
0      0.8         (Eggs)       1
1      0.6         (Milk)       1
2      0.6        (Onion)       1
3      0.6       (Yogurt)       1
4      0.6  (Onion, Eggs)       2

In [ ]:
df_ar = association_rules(frequent_itemsets, metric = "confidence", min_threshold = 0.7)
df_ar

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Onion),(Eggs),0.6,0.8,0.6,1.00,1.25,0.12,inf
1,(Eggs),(Onion),0.8,0.6,0.6,0.75,1.25,0.12,1.6

## **Resultados**

São geradas duas regras: {Onion} -> {Eggs} e {Eggs} -> {Onion}

Como a medida conviction é infinita na primeira regra, podemos dizer que esta é a melhor regra